FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache python3 py3-pip bash tini \
    && npm i -g concurrently@9.2.1

COPY docker/dev-entrypoint.sh /usr/local/bin/dev-entrypoint.sh
RUN chmod +x /usr/local/bin/dev-entrypoint.sh

EXPOSE 18789 5000
ENTRYPOINT ["/sbin/tini","--","/usr/local/bin/dev-entrypoint.sh"]
